### ISSUE TITLE
Este código no soporta multiples sistemas operativos.

### ISSUE THREAD

**Issue by matardy** [SbsCruz/semester-manager#1]
Este script asume que todos los usuarios tendrán windows, lo cual es un error. 
Adicionalmente: 
- Cada SO va a manejar abstracciones del sistema de archivos diferente, python tiene un modulo que resuelve eso, de esa forma el programador no va a tener que escribir / o \ manualmente. 
- Revisar los permisos de ejecución.

**Comment by Rikardo816** [comment]
@matardy La libreria para gestionar carpetas y permisos en multiples SO es la misma? solo una consulta.

**Comment by SbsCruz** [comment]
Hola matardy, con respecto a tu comentario, sería bueno que lo pruebes ahora para ver si ya está solucionado

**Comment by SbsCruz** [comment]
Matardy, te comento que el script ya es apto para sistemas operativos Windows y MacOS, un saludo

**Comment by matardy** [comment]
Gracias por corregirlo.
